sudo: false
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - "9.8"
  - "9.7"
  - "9.6"
  - "9.5"
  - "9.4"
  - "9.3"
  - "9.2"
  - "9.1"
  - "9.0"
  - "8.10"
  - "8.9"
  - "8.8"
  - "8.7"
  - "8.6"
  - "8.5"
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - "7.10"
  - "7.9"
  - "7.8"
  - "7.7"
  - "7.6"
  - "7.5"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "6.13"
  - "6.12"
  - "6.11"
script:
  - npm run test:ci
matrix:
  fast_finish: true
