sudo: false
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
script:
  - npm run test:ci
after_success:
  - npm run test:ci-coveralls
matrix:
  fast_finish: true
